In [2]:
import numpy as np
from numpy.linalg import eigh,norm

# get the word freuency matrix 
i have done its coding in separate file

In [3]:
#importing the library
from sklearn.feature_extraction.text import CountVectorizer
docs = ["i use my pen to write my book","i use my spectacles to read my book"]
vectorizer = CountVectorizer()
dictionary = vectorizer.fit_transform(docs)
print(vectorizer.get_feature_names())
print(dictionary.todense())

['book', 'my', 'pen', 'read', 'spectacles', 'to', 'use', 'write']
[[1 2 1 0 0 1 1 1]
 [1 2 0 1 1 1 1 0]]


so lets assign that word frequency matrix to a matrix named "wf"

In [11]:
wf = dictionary.todense()
print(wf)

[[1 2 1 0 0 1 1 1]
 [1 2 0 1 1 1 1 0]]


In [12]:
wf.T

matrix([[1, 1],
        [2, 2],
        [1, 0],
        [0, 1],
        [0, 1],
        [1, 1],
        [1, 1],
        [1, 0]], dtype=int64)

below code gives two matrices 

In [13]:
eigh(wf.T@wf)

(array([-1.02482984e-15, -1.36826427e-16, -7.76416999e-17,  2.01329472e-17,
         1.36240218e-16,  3.24163299e-15,  2.00000000e+00,  1.60000000e+01]),
 matrix([[-5.82178716e-01,  1.58194179e-01,  1.47774634e-01,
           7.66444875e-02, -5.98967624e-01, -3.52942785e-01,
          -9.37802184e-17,  3.53553391e-01],
         [ 2.01216233e-01,  3.10806607e-02,  3.74652461e-02,
           2.05522770e-02, -1.46820835e-01,  6.59669327e-01,
           1.63021835e-16,  7.07106781e-01],
         [-3.97423003e-01,  4.72010374e-01, -2.16091758e-01,
          -1.40873544e-01,  5.19352653e-01,  4.17490363e-02,
          -5.00000000e-01,  1.76776695e-01],
         [-2.93745892e-01, -2.02150532e-01, -5.82218274e-01,
           4.32182622e-01,  2.56222363e-01, -1.37359587e-02,
           5.00000000e-01,  1.76776695e-01],
         [-2.69591857e-01, -1.36520243e-01,  4.56311869e-01,
          -5.15621954e-01,  3.90877526e-01, -2.36789379e-02,
           5.00000000e-01,  1.76776695e-01],
         [ 

In [15]:
ev,v = eigh(wf.T@wf)
print(v)

[[-5.82178716e-01  1.58194179e-01  1.47774634e-01  7.66444875e-02
  -5.98967624e-01 -3.52942785e-01 -9.37802184e-17  3.53553391e-01]
 [ 2.01216233e-01  3.10806607e-02  3.74652461e-02  2.05522770e-02
  -1.46820835e-01  6.59669327e-01  1.63021835e-16  7.07106781e-01]
 [-3.97423003e-01  4.72010374e-01 -2.16091758e-01 -1.40873544e-01
   5.19352653e-01  4.17490363e-02 -5.00000000e-01  1.76776695e-01]
 [-2.93745892e-01 -2.02150532e-01 -5.82218274e-01  4.32182622e-01
   2.56222363e-01 -1.37359587e-02  5.00000000e-01  1.76776695e-01]
 [-2.69591857e-01 -1.36520243e-01  4.56311869e-01 -5.15621954e-01
   3.90877526e-01 -2.36789379e-02  5.00000000e-01  1.76776695e-01]
 [ 3.66351175e-01  1.76437238e-01  3.81743831e-01  4.91432791e-01
   3.28985543e-01 -4.62807401e-01 -9.63397412e-17  3.53553391e-01]
 [ 3.76732824e-01 -5.81219621e-02 -4.78542552e-01 -5.25742500e-01
  -8.34761383e-02 -4.66173573e-01 -1.55242210e-16  3.53553391e-01]
 [-1.65914747e-01 -8.10681149e-01  9.01853532e-02  5.74342122e-02
   

In [16]:
v[0]

matrix([[-5.82178716e-01,  1.58194179e-01,  1.47774634e-01,
          7.66444875e-02, -5.98967624e-01, -3.52942785e-01,
         -9.37802184e-17,  3.53553391e-01]])

In [17]:
v[:,0]

matrix([[-0.58217872],
        [ 0.20121623],
        [-0.397423  ],
        [-0.29374589],
        [-0.26959186],
        [ 0.36635118],
        [ 0.37673282],
        [-0.16591475]])

In [19]:
u0 = wf@v[:,0]/norm(wf@v[:,0])
print(u0)

[[0.7649112 ]
 [0.64413575]]


In [20]:
u1 = wf@v[:,1]/norm(wf@v[:,1])
print(u1)

[[ 0.70710678]
 [-0.70710678]]


In [22]:
u2 = wf@v[:,2]/norm(wf@v[:,2])
print(u2)

[[1.]
 [0.]]
